server:
  port: 3113

spring:
  application:
    name: EnglishKate
  datasource:
    url: "jdbc:h2:mem:EnglishKate"
    username: admin
    password: qwerty
  jpa:
    show-sql: true


h2:
  console: enabled